language: java
dist: trusty
sudo: false
install: true

addons:
  branches:
    - master
    - develop
jdk:
  - openjdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -DskipDocker -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dspring.mail.username=$MAIL_USERNAME -Dspring.mail.password=$MAIL_PASSWORD -Dtrakt.appId=$traktAppId -Dtrakt.appSecret=$traktAppSecret

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
