dispatchd:
  config:
    test: config_config_contentservice_yml
content:
    refresh:
        interval:
            minutes: 1
trakt:
  baseServiceUrl: https://api.trakt.tv
  appId : superSecretAppIdFromTrakt
  appSecret : superSecretAppSecretFromTrakt
  apiVersion : 2
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8010"
#        expose all actuator endpoints for SBA
management:
  endpoints:
    web:
      exposure:
        include: "*"
