content:
    refresh:
        interval:
            minutes: 1
trakt:
  baseServiceUrl: https://api.trakt.tv
  appId : superSecretAppIdFromTrakt
  appSecret : superSecretAppSecretFromTrakt
  apiVersion : 2
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8010"
#        expose all actuator endpoints for SBA
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
