dispatchd:
  config:
    test: config_config_contentservice_yml
content:
    refresh:
        interval:
            minutes: 1
trakt:
  baseServiceUrl: https://api.trakt.tv
  appId : superSecretAppIdFromTrakt
  appSecret : superSecretAppSecretFromTrakt
  apiVersion : 2
