server:
  port: 8010
management:
  security:
    enabled: false
  context-path: /actuator
spring:
  boot:
    admin:
      username: mgmtuser
      password: password
      client:
        management-url: /actuator
  application:
    name: Dispatchd Monitor service
zuul:
  sensitive-headers:
security:
  user:
    name: defaultuser
    password: password
