content:
    refresh:
        interval:
            minutes: 1
report:
    generation:
        interval:
            seconds: 60
spring:
    application:
        name: coreService
    boot:
      admin:
        client:
          url: "http://localhost:8010"
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    messages:
        basename: messages/Messages
management:
  endpoints:
    web:
      exposure:
        include: "*"
