spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    password:
    url: jdbc:h2:~/workspace/dispatchd/dispatchddb
    username: sa
logging:
  level:
    com.sandjelkovic: DEBUG
management:
  security:
    enabled: false
