server:
  port: 8888
spring:
  application:
    name: configserver
  config:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/
  security:
    user:
      password: 1234 #the password which apps will use to access its configurations
logging:
  level:
    com.sandjelkovic: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: false
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
